### ISSUE TITLE
Cannot scan QR code.

### ISSUE THREAD

**Issue by baklim** [kryptco/kr#93]
Device: Xiaomi Redmi Note 3
ROM: LineageOS 13 (Android MM)
logcat:
```
LAUNCHER] flg=0x10200000 cmp=co.krypt.kryptonite/.MainActivity} from uid 10203 on display 0
05-05 12:45:09.144  2318  3679 I ActivityManager: START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:co.krypt.kryptonite cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10025 on display 0
05-05 12:47:16.176   481 26314 I CameraService: CameraService::connect call (PID 25652 "co.krypt.kryptonite", camera ID 0) for HAL version default and Camera API version 1
05-05 12:47:16.176   481 26314 I Camera2ClientBase: Camera 0: Opened. Client: co.krypt.kryptonite (PID 25652, UID 10119)
05-05 12:47:16.639 25652 25652 E BarcodeNativeHandle:   at co.krypt.kryptonite.pairing.PairScanner.<init>(PairScanner.java:50)
05-05 12:47:16.639 25652 25652 E BarcodeNativeHandle:   at co.krypt.kryptonite.pairing.PairFragment$5$1.run(PairFragment.java:303)
05-05 12:47:16.644 25652 25652 E BarcodeNativeHandle:   at co.krypt.kryptonite.pairing.PairScanner.<init>(PairScanner.java:51)
05-05 12:47:16.644 25652 25652 E BarcodeNativeHandle:   at co.krypt.kryptonite.pairing.PairFragment$5$1.run(PairFragment.java:303)
05-05 12:47:27.685   481  3074 I Camera2ClientBase: Closed Camera 0. Client was: co.krypt.kryptonite (PID 25652, UID 10119)
```

**Comment by baklim** [comment]
Sorry, wrong place.
